### ISSUE TITLE
I have made another cuda-fi version

### ISSUE THREAD

**Issue by gleonn** [UFRGS-CAROL/carol-fi#2]
They are change from the carol_fu_cuda_parrallel branch and uploaded to
https://github.com/gleonn/carol-fi-cuda.git.  I hope you don't mind, I want to reference it in an article. I said it if you want to integrate it @dagoliveira

**Comment by fernandoFernandeSantos** [comment]
Hello, no problem at all; I'm happy to see that people are using CAROL-FI. 
If you find things that can be improved, please submit a pull request so that we can also integrate them on the CUDA branch.
Thanks
